data_module:
  _target_: module.datamodule.DataModule
  train_dataset_path: "/jbod/rokubo/ELNESDiff/dataset/Si_O_ELNES/Si_O_ELNES_train.pt"
  val_dataset_path: "/jbod/rokubo/ELNESDiff/dataset/Si_O_ELNES/Si_O_ELNES_valid.pt"
  test_dataset_path: "/jbod/rokubo/ELNESDiff/dataset/Si_O_ELNES/Si_O_ELNES_test.pt"
  batch_size: 32
  num_workers: 1
  pin_memory: False
  normalize: sum

lightning_module:
  _target_: module.lightningmodule.LightningModule
  model:
    _target_: module.EquivariantGraphNeuralNetwork.EquivariantGNN
    L: 5
    m_input: 400
    m_hidden: 256
    m_output: 512
    x_input: 3
    x_hidden: 128
    x_output: 256
    h_input: 712
    h_hidden: 512
    h_output: 200
    total_output_dim: 5
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: True
    lr: 1e-4
    weight_decay: 1e-5
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: True
    mode: min
    factor: 0.5
    patience: 30
    min_lr: 1e-6
