defaults:
  - _self_
  - stage: train
  - module: default

seed: 42
ymd: ${now:%Y-%m-%d}
hms: ${now:%H-%M-%S}


hydra:
  run:
    dir: /jbod/rokubo/ELNESDiff/egnn_pred/outputs/${ymd}/${hms}/${stage.mode}