mode: train

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 3000
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_loss
      mode: min
      save_top_k: 1
      filename: "best_model"
      dirpath: /jbod/rokubo/ELNESDiff/egnn_pred/outputs/${ymd}/${hms}/${stage.mode}/checkpoints
  logger:
    - _target_: pytorch_lightning.loggers.WandbLogger
      project: "ELNESDiff"
      name: "spectrum_only_pred_${ymd}_${hms}"
      save_dir: /jbod/rokubo/ELNESDiff/egnn_pred/outputs/${ymd}/${hms}/${stage.mode}/logs
      resume: "allow"
      tags:
        - "spectrum_only_pred"